USE [master]
GO

/****** Object:  Database [EnergyData]    Script Date: 04/06/2014 16:49:05 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'EnergyData')
DROP DATABASE [EnergyData]
GO

USE [master]
GO

/****** Object:  Database [EnergyData]    Script Date: 04/06/2014 16:49:05 ******/
CREATE DATABASE [EnergyData] 

ALTER DATABASE [EnergyData] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EnergyData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EnergyData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EnergyData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EnergyData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EnergyData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EnergyData] SET ARITHABORT OFF 
GO

ALTER DATABASE [EnergyData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EnergyData] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EnergyData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EnergyData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EnergyData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EnergyData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EnergyData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EnergyData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EnergyData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EnergyData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EnergyData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EnergyData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EnergyData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EnergyData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EnergyData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EnergyData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EnergyData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EnergyData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EnergyData] SET  READ_WRITE 
GO

ALTER DATABASE [EnergyData] SET RECOVERY FULL 
GO

ALTER DATABASE [EnergyData] SET  MULTI_USER 
GO

ALTER DATABASE [EnergyData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EnergyData] SET DB_CHAINING OFF 
GO


